# Base image for testing MyAsyncFramework.
# Build from repo root: yamo framework test *test arguments* 

FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

COPY my-async-framework /app/my-async-framework

WORKDIR /app/my-async-framework

RUN cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DLOG_LEVEL=3 -DBUILD_TESTING=ON && \
    cmake --build build && \
    cmake --install build --prefix /usr/local

WORKDIR /app/my-async-framework/build